version: "3.9"

services:
  db:
    image: postgres:16
    container_name: kindinout-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: kindinout
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d kindinout"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data:
